### PR TITLE
add: new CDN orange into the list

### PR DESCRIPTION
**Pull request by schampseix-orange**
We want to add our CDN into the list

If you have any question about this request let me know

Best regards
sebastien

### CODE REVIEW

**Comment by pmeenan** [comment]
Do you have details about the CDN (maybe a network map of edges or a few static assets I can test)? I just need to make sure it is a geo-distributed CDN before merging.

**Comment by schampseix-orange** [comment]
Hi @pmeenan ,

You can see some cdn call through the website : https://www.orange.fr

https://proxymedia.woopic.com/api/v1/images/1154/p/gp/20191014-14-27-15/1200x313-GeneriqueLaBoiteSosh.png?crop=960,250,right,32
https://c.woopic.com/logo-orange.png
https://c.woopic.com/Magic/567x302_megamenu_Cashback.jpg
https://cdn.woopic.com/18d8339538654b1dbf96a30e92745731/fonts/icon-orange.8f558d2ade8b5038ab2d9ec35a79e04f.woff2

Best regards,
sebastien

**Comment by pmeenan** [comment]
Thanks.  Do you know what the geo distribution looks like?  Is it at least distributed across Europe?  The RTT from the US east coast is 90ms and from the west coast is 150ms.  From Sydney it is closer to 330ms.

Best-case is that it is a Europe-specific CDN for Orange that is geo-distributed across Europe but it looks a loot like a load-balancer for availability and a static content server without geo-targeting for latency reduction.

**Comment by pmeenan** [comment]
Closing.  Feel free to re-open with details about the geo-distribution of the edge nodes.

**Pull request closed without merging**
