### PR TITLE
lighthouse for current browser session

### PR DESCRIPTION
**Pull request by imkalvin**
Hi @pmeenan,

In my org, we need to test against pages behind authentication (which was identified with a cookie with max-age=session). With these changes, WPT is now able to do that (tested on Windows+Ubuntu 18.04).

Pls help to take a look whether this is something WPT wants to take in.

This might also address the issue https://github.com/WPO-Foundation/wptagent/issues/395

### CODE REVIEW

**Comment by pmeenan** [comment]
It might be better if the capability was an option so it could be enabled explicitly when desired.  Otherwise there is no way to get a "clean" lighthouse test with no cookies or cache populated.

**Comment by imkalvin** [comment]
> It might be better if the capability was an option so it could be enabled explicitly when desired. Otherwise there is no way to get a "clean" lighthouse test with no cookies or cache populated.

Then I assume we will need to enhance the server part to add a new option, then pass along to agents...right?

**Comment by pmeenan** [comment]
Either an explicit option or only use this mode when a script is provided.  I'm happy to plumb the test setting if you're worried about the php side of things (it's just index.php and runtest.php and can be copied from some of the other options)

**Comment by imkalvin** [comment]
> Either an explicit option or only use this mode when a script is provided. I'm happy to plumb the test setting if you're worried about the php side of things (it's just index.php and runtest.php and can be copied from some of the other options)

Thanks @pmeenan ! 

I think using this mode when  a script is provided will make better sense. I will update the PR later.

**Comment by imkalvin** [comment]
Hi @pmeenan ,

I had wrapped the new logic with a flag check upon task['script']. Pls help to review and proceed. Thanks!

**Comment by M-Z** [comment]
Hi,
I gave this a try and it worked as it should for me.
Would be great if this is confirmed to patch my agents with it.

**Comment by eugeneidoronin** [comment]
If it works that would be great to have it merged. Thank you.

**Comment by pmeenan** [comment]
I need to double-check but I think the non-script case may also trigger it because a simple URL test is also converted into a 1-step navigate script.  I think the reuse check need to check that the script length > 1 instead of > 0

**Pull request closed without merging**
