### PR TITLE
Collect stats from wasm files

### PR DESCRIPTION
**Pull request by pmeenan**
This adds extraction of WASM stats from wasm binaries using a [fork](https://github.com/HTTPArchive/wasm-stats) of the tool used for last year's web almanac (modified to run on individual wasm files).

It adds a pre-built binary (and only works on) 64-bit linux x86 (pretty much all VM-based WPT agents). It is optimized for size as much as possible but is still adding a 400KB binary blob to the repo (we have binary blobs for tcpdump and tethering code so that's not that out of the ordinary). If there is interest, I can also add MacOS and Raspberry Pi binaries but I expect Linux will cover most needs.

Fixes https://github.com/WPO-Foundation/wptagent/issues/437
Fixes https://github.com/HTTPArchive/almanac.httparchive.org/issues/2914

### CODE REVIEW

**Comment by tkadlec** [comment]
Looking solid! 

> If there is interest, I can also add MacOS and Raspberry Pi binaries 

How hard would it be to add the MacOS binary here?

**Comment by pmeenan** [comment]
On it.  Installing Rust on my MacOS system now. Will update the PR shortly

**Comment by pmeenan** [comment]
Done. Looks like the MacOS binary was a little bit smaller (385kb)

**Comment by pmeenan** [comment]
@tkadlec ping.

Not urgent but this is the only patch we use in the HTTP Archive that is still separate.

**Pull request merged**
