### PR TITLE
Update optimization_checks.py - Added new CDN

### PR DESCRIPTION
**Pull request by mantico91**
Added new proprietary CDN

### CODE REVIEW

**Comment by pmeenan** [comment]
What is a "proprietary CDN" and does it apply to multiple websites (i.e. is it freely or commercially available for people to sign-up with)?

Is there documentation showing the geographic distribution of POPs and how they are selected (to make sure it is globally distributing client connections based on performance)?

**Comment by tkadlec** [comment]
Gonna close this for now. @mantico91, if you've got a bit more info about the CDN, let us know here so we can determine if it fits to be added in.

**Comment by mantico91** [comment]
Hi tkadlec,

Sorry for not answered at your reply.

We Are organizing the documentation.

Sorry again!

See you soon

M.
________________________________
Da: tkadlec ***@***.***>
Inviato: Thursday, April 21, 2022 9:34:00 PM
A: WPO-Foundation/wptagent ***@***.***>
Cc: Massimiliano Savelli ***@***.***>; Mention ***@***.***>
Oggetto: Re: [WPO-Foundation/wptagent] Update optimization_checks.py - Added new CDN (PR #455)


Closed #455<https://github.com/WPO-Foundation/wptagent/pull/455>.

**Comment by mantico91** [comment]
Hi tkadlec,
here you can find all info about our CDN
https://www.ismartframe.com/en/isf-cdn/
Thank in advance

Hi, above the reply to the closed commit.

Should I re-make a new pull request?

Thank you


[signature_711531100]
[signature_793732550]<https://www.instagram.com/holocron_srl/?hl=it>  [signature_880941300] <https://www.facebook.com/holocronsrl/>   [signature_1280401186] <https://www.linkedin.com/company/holocron/>   [signature_483534598] <https://www.linkedin.com/company/holocron/>
Massimiliano Savelli

Senior Developer | Holocron S.r.l.

Fino a 3 ore fa funzionava tutto

 {
      "phone": {
            "office": "+39 050 500 525",
            "mobile": "+39 340 144 9423"
      },
      "mail": ***@***.***",
      "url":  "https://holocron.it/",
      "sede": {
            "operativa": "Via Pasquale Pardi 9, 56121, Pisa (PI)",
            "legale": "Via Garibaldi 65, 56124, Pisa (PI)"
      }
}
The company accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information
provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing,
copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.


Da: tkadlec ***@***.***>
Data: giovedì, 21 aprile 2022, 21:34
A: WPO-Foundation/wptagent ***@***.***>
Cc: Massimiliano Savelli ***@***.***>, Mention ***@***.***>
Oggetto: Re: [WPO-Foundation/wptagent] Update optimization_checks.py - Added new CDN (PR #455)

Closed #455<https://github.com/WPO-Foundation/wptagent/pull/455>.

**Pull request closed without merging**
