### PR TITLE
Fixed Dockerfile build. added apt-get.txt, changed entrypoint.sh

### PR DESCRIPTION
**Pull request by sammeboy635**
Fixed Dockerfile build:
- We can build directly from GitHub repo link with "docker build GITHUB-REPO-LINK -t TAGNAME"
- Added docker-apt-get.txt for all the apt-get package names
- Entrypoint.sh changed to python3, added new argument by default (-vvvv)
- Reduced Dockerfile container size from 2.7 GB to 1.3 GB (unfortunately still takes about 10 minutes to build)

Tried to see if we could run "sudo modprobe ifb numifbs=1" inside of the container for traffic shaping but I didn't have any luck with that.

image

I did get a few successful runs in with the old wpt/server docker image and the new image created.
MicrosoftTeams-image

"python3 wptagent.py -vvvv --xvfb --dockerized --testurl www.google.com --shaper none"
image

### CODE REVIEW

**Comment by deathbearbrown** [comment]
Can you try running this fresh? I get an error about an ubuntu release that it's trying to get that is EOL as of the end of July. I don't know if this is a me problem...

**Comment by sammeboy635** [comment]
> Can you try running this fresh? I get an error about an ubuntu release that it's trying to get that is EOL as of the end of July. I don't know if this is a me problem...

Of course, Thanks for letting me know! I have to recheck some aspects of this project anyways, because currently I think this docker container can't communicate to Webpagetest docker because of some small network configurations needed. 
@deathbearbrown What OS are you currently using by the way?

**Comment by deathbearbrown** [comment]
I'm using macOS Montery 12.5.1

**Comment by sammeboy635** [comment]
> I'm using macOS Monterey 12.5.1

**Pull request merged**
